#!/usr/bin/env python3
"""Generate ``src/digits.rs``: the Unicode decimal-digit runs.

Python's `Decimal` accepts any Unicode decimal digit, so `Decimal("٥")` is 5 and
`Decimal("੨")` is 2. `rust_decimal` accepts only ASCII, which made this port
silently return `None` for prices written in Arabic-Indic, Devanagari, Bengali
and other numerals -- found by `tools/fuzz_diff.py`, not by the test suite.

Every character in general category `Nd` belongs to a contiguous run of ten,
starting at the character for zero. Recording the start of each run is therefore
enough to recover any digit's value by subtraction, with no per-character table.

    python tools/gen_unicode_digits.py
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import unicodedata
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "src" / "digits.rs"


def decimal_run_starts() -> list[int]:
    """The code point of 'zero' for every Nd run, ascending."""
    starts = {
        cp - unicodedata.decimal(chr(cp))
        for cp in range(0x110000)
        if unicodedata.category(chr(cp)) == "Nd"
    }
    return sorted(starts)


def render(starts: list[int]) -> str:
    rows = "".join(
        f"    0x{start:05x}, // {unicodedata.name(chr(start), '?')}\n" for start in starts
    )
    return f'''//! Unicode decimal-digit runs.
//!
//! @generated by `tools/gen_unicode_digits.py` -- DO NOT EDIT BY HAND.
//!
//! Python's `Decimal` accepts any Unicode decimal digit, so `Decimal("٥")` is
//! 5. `rust_decimal` accepts only ASCII, so digits have to be folded down
//! before parsing or prices written in non-Latin numerals silently vanish.
//!
//! Every character in general category `Nd` sits in a contiguous run of ten
//! beginning at that script's zero, so the run starts alone are enough to
//! recover any digit's value by subtraction.
//!
//! Unicode {unicodedata.unidata_version}, {len(starts)} runs.

/// Code point of the zero character for each decimal-digit run, ascending.
const DECIMAL_RUN_STARTS: [u32; {len(starts)}] = [
{rows}];

/// The numeric value of `c`, if it is a Unicode decimal digit.
///
/// ```
/// use price_parser::digits::decimal_digit_value;
///
/// assert_eq!(decimal_digit_value('7'), Some(7));
/// assert_eq!(decimal_digit_value('٥'), Some(5)); // Arabic-Indic five
/// assert_eq!(decimal_digit_value('੨'), Some(2)); // Gurmukhi two
/// assert_eq!(decimal_digit_value('x'), None);
/// ```
pub fn decimal_digit_value(c: char) -> Option<u32> {{
    let cp = c as u32;
    // ASCII is overwhelmingly the common case; skip the search for it.
    if c.is_ascii_digit() {{
        return Some(cp - u32::from(b'0'));
    }}
    let index = DECIMAL_RUN_STARTS.partition_point(|&start| start <= cp);
    let start = DECIMAL_RUN_STARTS.get(index.checked_sub(1)?)?;
    let value = cp - start;
    (value < 10).then_some(value)
}}

/// Rewrite every Unicode decimal digit in `text` as its ASCII equivalent.
///
/// Non-digits are left exactly as they are. Returns `None` when nothing needed
/// changing, so the common all-ASCII path allocates nothing.
pub fn fold_decimal_digits(text: &str) -> Option<String> {{
    if text.chars().all(|c| !c.is_numeric() || c.is_ascii_digit()) {{
        return None;
    }}
    Some(
        text.chars()
            .map(|c| match decimal_digit_value(c) {{
                Some(value) => char::from_digit(value, 10).unwrap_or(c),
                None => c,
            }})
            .collect(),
    )
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    starts = decimal_run_starts()
    generated = render(starts)

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        tmp = args.output.with_suffix(".rs.check")
        # newline="\n" explicitly: the default translates to CRLF on Windows,
        # so the same input would produce a different file per platform and the
        # check below would fail for reasons unrelated to its contents.
        tmp.write_text(generated, encoding="utf-8", newline="\n")
        try:
            if shutil.which("rustfmt"):
                subprocess.run(["rustfmt", "--edition", "2021", str(tmp)], check=True,
                               capture_output=True)
            stale = tmp.read_text(encoding="utf-8") != current
        finally:
            tmp.unlink(missing_ok=True)
        if stale:
            print(f"{args.output} is stale -- re-run tools/gen_unicode_digits.py")
            return 1
        print(f"{args.output.relative_to(REPO_ROOT)} is up to date")
        return 0

    args.output.write_text(generated, encoding="utf-8", newline="\n")
    if shutil.which("rustfmt"):
        subprocess.run(["rustfmt", "--edition", "2021", str(args.output)], check=True,
                       capture_output=True)

    print(f"wrote {args.output.relative_to(REPO_ROOT)}")
    print(f"  Unicode version : {unicodedata.unidata_version}")
    print(f"  decimal runs    : {len(starts)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
