//! Unicode decimal-digit runs.
//!
//! @generated by `tools/gen_unicode_digits.py` -- DO NOT EDIT BY HAND.
//!
//! Python's `Decimal` accepts any Unicode decimal digit, so `Decimal("٥")` is
//! 5. `rust_decimal` accepts only ASCII, so digits have to be folded down
//! before parsing or prices written in non-Latin numerals silently vanish.
//!
//! Every character in general category `Nd` sits in a contiguous run of ten
//! beginning at that script's zero, so the run starts alone are enough to
//! recover any digit's value by subtraction.
//!
//! Unicode 15.0.0, 68 runs.

/// Code point of the zero character for each decimal-digit run, ascending.
const DECIMAL_RUN_STARTS: [u32; 68] = [
    0x00030, // DIGIT ZERO
    0x00660, // ARABIC-INDIC DIGIT ZERO
    0x006f0, // EXTENDED ARABIC-INDIC DIGIT ZERO
    0x007c0, // NKO DIGIT ZERO
    0x00966, // DEVANAGARI DIGIT ZERO
    0x009e6, // BENGALI DIGIT ZERO
    0x00a66, // GURMUKHI DIGIT ZERO
    0x00ae6, // GUJARATI DIGIT ZERO
    0x00b66, // ORIYA DIGIT ZERO
    0x00be6, // TAMIL DIGIT ZERO
    0x00c66, // TELUGU DIGIT ZERO
    0x00ce6, // KANNADA DIGIT ZERO
    0x00d66, // MALAYALAM DIGIT ZERO
    0x00de6, // SINHALA LITH DIGIT ZERO
    0x00e50, // THAI DIGIT ZERO
    0x00ed0, // LAO DIGIT ZERO
    0x00f20, // TIBETAN DIGIT ZERO
    0x01040, // MYANMAR DIGIT ZERO
    0x01090, // MYANMAR SHAN DIGIT ZERO
    0x017e0, // KHMER DIGIT ZERO
    0x01810, // MONGOLIAN DIGIT ZERO
    0x01946, // LIMBU DIGIT ZERO
    0x019d0, // NEW TAI LUE DIGIT ZERO
    0x01a80, // TAI THAM HORA DIGIT ZERO
    0x01a90, // TAI THAM THAM DIGIT ZERO
    0x01b50, // BALINESE DIGIT ZERO
    0x01bb0, // SUNDANESE DIGIT ZERO
    0x01c40, // LEPCHA DIGIT ZERO
    0x01c50, // OL CHIKI DIGIT ZERO
    0x0a620, // VAI DIGIT ZERO
    0x0a8d0, // SAURASHTRA DIGIT ZERO
    0x0a900, // KAYAH LI DIGIT ZERO
    0x0a9d0, // JAVANESE DIGIT ZERO
    0x0a9f0, // MYANMAR TAI LAING DIGIT ZERO
    0x0aa50, // CHAM DIGIT ZERO
    0x0abf0, // MEETEI MAYEK DIGIT ZERO
    0x0ff10, // FULLWIDTH DIGIT ZERO
    0x104a0, // OSMANYA DIGIT ZERO
    0x10d30, // HANIFI ROHINGYA DIGIT ZERO
    0x11066, // BRAHMI DIGIT ZERO
    0x110f0, // SORA SOMPENG DIGIT ZERO
    0x11136, // CHAKMA DIGIT ZERO
    0x111d0, // SHARADA DIGIT ZERO
    0x112f0, // KHUDAWADI DIGIT ZERO
    0x11450, // NEWA DIGIT ZERO
    0x114d0, // TIRHUTA DIGIT ZERO
    0x11650, // MODI DIGIT ZERO
    0x116c0, // TAKRI DIGIT ZERO
    0x11730, // AHOM DIGIT ZERO
    0x118e0, // WARANG CITI DIGIT ZERO
    0x11950, // DIVES AKURU DIGIT ZERO
    0x11c50, // BHAIKSUKI DIGIT ZERO
    0x11d50, // MASARAM GONDI DIGIT ZERO
    0x11da0, // GUNJALA GONDI DIGIT ZERO
    0x11f50, // KAWI DIGIT ZERO
    0x16a60, // MRO DIGIT ZERO
    0x16ac0, // TANGSA DIGIT ZERO
    0x16b50, // PAHAWH HMONG DIGIT ZERO
    0x1d7ce, // MATHEMATICAL BOLD DIGIT ZERO
    0x1d7d8, // MATHEMATICAL DOUBLE-STRUCK DIGIT ZERO
    0x1d7e2, // MATHEMATICAL SANS-SERIF DIGIT ZERO
    0x1d7ec, // MATHEMATICAL SANS-SERIF BOLD DIGIT ZERO
    0x1d7f6, // MATHEMATICAL MONOSPACE DIGIT ZERO
    0x1e140, // NYIAKENG PUACHUE HMONG DIGIT ZERO
    0x1e2f0, // WANCHO DIGIT ZERO
    0x1e4f0, // NAG MUNDARI DIGIT ZERO
    0x1e950, // ADLAM DIGIT ZERO
    0x1fbf0, // SEGMENTED DIGIT ZERO
];

/// The numeric value of `c`, if it is a Unicode decimal digit.
///
/// ```
/// use price_parser::digits::decimal_digit_value;
///
/// assert_eq!(decimal_digit_value('7'), Some(7));
/// assert_eq!(decimal_digit_value('٥'), Some(5)); // Arabic-Indic five
/// assert_eq!(decimal_digit_value('੨'), Some(2)); // Gurmukhi two
/// assert_eq!(decimal_digit_value('x'), None);
/// ```
pub fn decimal_digit_value(c: char) -> Option<u32> {
    let cp = c as u32;
    // ASCII is overwhelmingly the common case; skip the search for it.
    if c.is_ascii_digit() {
        return Some(cp - u32::from(b'0'));
    }
    let index = DECIMAL_RUN_STARTS.partition_point(|&start| start <= cp);
    let start = DECIMAL_RUN_STARTS.get(index.checked_sub(1)?)?;
    let value = cp - start;
    (value < 10).then_some(value)
}

/// Rewrite every Unicode decimal digit in `text` as its ASCII equivalent.
///
/// Non-digits are left exactly as they are. Returns `None` when nothing needed
/// changing, so the common all-ASCII path allocates nothing.
pub fn fold_decimal_digits(text: &str) -> Option<String> {
    if text.chars().all(|c| !c.is_numeric() || c.is_ascii_digit()) {
        return None;
    }
    Some(
        text.chars()
            .map(|c| match decimal_digit_value(c) {
                Some(value) => char::from_digit(value, 10).unwrap_or(c),
                None => c,
            })
            .collect(),
    )
}
